# Development
#url: http://localhost:4000

# Production
url: http://tinyfactory.github.com/TF-Policy-Docs

permalink: :date

domain: http://tinyfactory.github.com
title: Tiny Factory Policy Docs
author: Tiny Factory
email: hello@tinyfactory.co

#google_analytics:
#  account: UA-20145334-1

prose:
  rooturl: "_posts"